import json
import re
from pathlib import Path

# Paths
import sys
from pathlib import Path

# Get Job ID from args or default
job_id = sys.argv[1] if len(sys.argv) > 1 else "59f7419b"

# Paths
job_dir = Path(r"c:\Users\email\Downloads\AI-Document-presentation\ai-doc-presentation\player\jobs") / job_id
pres_path = job_dir / "presentation.json"
code_path = job_dir / "manim_code" / "section_3.py" # TODO: Make section configurable too if needed

print(f"--- ANALYZING JOB: {job_id} ---")

# 1. Analyze Presentation JSON (Targets)
if not pres_path.exists():
    print("ERROR: presentation.json not found")
else:
    with open(pres_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    sections = data.get("sections", [])
    # Find Section 3
    sec3 = next((s for s in sections if s.get("section_id") == 3 or s.get("id") == 3), None)
    
    if sec3:
        print(f"\n[SECTION 3 TARGETS]")
        segments = sec3.get("narration", {}).get("segments", [])
        total_narration_time = 0
        for i, seg in enumerate(segments):
            dur = seg.get("duration", 0)
            total_narration_time += dur
            print(f"  Segment {i}: {dur:.2f}s | Text: {seg.get('text', '')[:30]}...")
        print(f"  TOTAL TARGET DURATION: {total_narration_time:.2f}s")
    else:
        print("ERROR: Section 3 not found in JSON")

# 2. Analyze Manim Code (Actuals)
if not code_path.exists():
    print("\nERROR: section_3.py not found")
else:
    print(f"\n[MANIM CODE TIMING ESTIMATES]")
    with open(code_path, "r", encoding="utf-8") as f:
        code_lines = f.readlines()
    
    current_segment = -1
    segment_time = 0
    total_code_time = 0
    
    print("  (Parsing run_time and wait calls...)")
    
    for line in code_lines:
        line = line.strip()
        
        # Detect comment indicating segment start (if generated by V2 prompt)
        if "# Segment" in line:
            if current_segment >= 0:
                print(f"  -> Segment {current_segment} Calculated Duration: {segment_time:.2f}s")
            
            # Reset for next segment
            current_segment += 1
            segment_time = 0
            # Try to parse the target line from comment "Duration 12.5s"
            target_match = re.search(r"duration\s*([\d\.]+)", line, re.IGNORECASE)
            target_str = f"(Target: {target_match.group(1)}s)" if target_match else ""
            print(f"  Scanning Segment {current_segment} {target_str}...")
            continue
            
        # Parse run_time
        rt_match = re.search(r"run_time\s*=\s*([\d\.]+)", line)
        if rt_match:
            val = float(rt_match.group(1))
            segment_time += val
            total_code_time += val
            
        # Parse wait
        wait_match = re.search(r"self\.wait\s*\(\s*([\d\.]+)", line)
        if wait_match:
            val = float(wait_match.group(1))
            segment_time += val
            total_code_time += val
            
    # Print last segment
    if current_segment >= 0:
         print(f"  -> Segment {current_segment} Calculated Duration: {segment_time:.2f}s")
    
    print(f"  TOTAL MANIM CODE DURATION: {total_code_time:.2f}s")
