"""
Test v2.5-partition-director pipeline with validator
"""
import requests
import json
import time
from pathlib import Path

print("=" * 80)
print("TESTING v2.5-partition-director PIPELINE")
print("=" * 80)

# Read test markdown
test_file = Path("tests/test_pythagorean.md")

print(f"\n✓ Test file found: {test_file}")

# Submit job with specific pipeline
print("\n[1/3] Submitting test job (pipeline_version=v2.5-partition-director)...")
try:
    with open(test_file, 'rb') as f:
        files = {'file': ('test_pythagorean.md', f, 'text/markdown')}
        data = {
            'subject': 'Mathematics',
            'grade': '9',
            'dry_run': 'true',
            'pipeline_version': 'v2.5-partition-director',  # SPECIFIC PIPELINE
            'skip_wan': 'true'
        }
        
        response = requests.post('http://localhost:5000/submit_job', files=files, data=data)
        result = response.json()
        
        if response.status_code == 200:
            job_id = result['job_id']
            print(f"✓ Job submitted: {job_id}")
            print(f"  Pipeline: v2.5-partition-director")
            print(f"  Dry run: {result['dry_run']}")
        else:
            print(f"✗ Failed: {result}")
            exit(1)
except Exception as e:
    print(f"✗ Error: {e}")
    exit(1)

# Monitor job
print(f"\n[2/3] Monitoring job {job_id}...")
max_wait = 150
start_time = time.time()

while time.time() - start_time < max_wait:
    try:
        response = requests.get(f'http://localhost:5000/job/{job_id}/status')
        status_data = response.json()
        
        current_status = status_data['status']
        current_step = status_data.get('current_step', '')
        
        print(f"  Status: {current_status} | Step: {current_step}")
        
        if current_status == 'completed':
            print(f"\n✓ Job completed!")
            break
        elif current_status == 'failed':
            error = status_data.get('error', 'Unknown')
            print(f"\n✗ Job failed: {error}")
            exit(1)
        
        time.sleep(5)
    except Exception as e:
        print(f"  Error: {e}")
        time.sleep(5)

if time.time() - start_time >= max_wait:
    print(f"\n✗ Timeout")
    exit(1)

# Check for validator artifacts
print(f"\n[3/3] Checking for Content Completeness Validator artifacts...")
job_dir = Path(f"player/jobs/{job_id}")

# Check artifacts directory
artifacts_dir = job_dir / "artifacts"
validation_file = artifacts_dir / "completeness_validation.json"

if validation_file.exists():
    print(f"  ✓ PASS: Validation file exists!")
    with open(validation_file, 'r') as f:
        validation_data = json.load(f)
    print(f"  ✓ Validation status: {validation_data.get('validation_status')}")
    print(f"  ✓ Validator executed successfully!")
else:
    print(f"  ✗ FAIL: Validation file NOT found")
    print(f"  ✗ Artifacts directory: {artifacts_dir.exists()}")
    if artifacts_dir.exists():
        files = list(artifacts_dir.glob("*"))
        print(f"  ✗ Files in artifacts: {[f.name for f in files]}")

# Check presentation metadata
pres_path = job_dir / "presentation.json"
if pres_path.exists():
    with open(pres_path, 'r') as f:
        pres = json.load(f)
    
    metadata = pres.get('metadata', {})
    
    print(f"\n  Presentation metadata:")
    print(f"    Pipeline mode: {metadata.get('pipeline_mode')}")
    print(f"    Generated by: {metadata.get('generated_by')}")
    print(f"    Validation passed: {metadata.get('validation_passed_first_attempt', 'N/A')}")
    print(f"    Validation retry: {metadata.get('validation_retry', 'N/A')}")
    print(f"    Validation failed (dry-run): {metadata.get('validation_failed_dry_run', 'N/A')}")

print(f"\n" + "=" * 80)
print(f"Test completed for job: {job_id}")
print(f"=" * 80)
