import json
from pathlib import Path

JOB_ID = "d1c34c5f"
JSON_PATH = Path(f"player/jobs/{JOB_ID}/presentation.json")

def inspect_metadata():
    if not JSON_PATH.exists():
        print("❌ presentation.json NOT FOUND")
        return
        
    try:
        with open(JSON_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
            
        print(f"✅ Loaded presentation.json")
        
        meta = data.get("metadata", {})
        print("Metadata:")
        print(json.dumps(meta, indent=2))
        
        gen_by = meta.get("generated_by", "UNKNOWN")
        print(f"\nGenerated By: '{gen_by}'")
        
        if gen_by == "v1.5-v2.5-director":
             print("✅ Metadata confirms Director Mode.")
        else:
             print("❌ Metadata indicates LEGACY/WRONG generator.")

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    inspect_metadata()
