import json
from pathlib import Path

JOB_ID = "f3c9afc7"
JSON_PATH = Path(f"player/jobs/{JOB_ID}/presentation.json")

def inspect_metadata_v2():
    print(f"Inspecting metadata for {JOB_ID}...")
    if not JSON_PATH.exists():
        print("❌ presentation.json NOT FOUND (Still Processing)")
        return
        
    try:
        with open(JSON_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
            
        meta = data.get("metadata", {})
        gen_by = meta.get("generated_by", "UNKNOWN")
        
        print(f"✅ FOUND presentation.json")
        print(f"Generated By: '{gen_by}'")
        
        if gen_by == "v1.5-v2.5-director":
             print("🎉 RESULT: SUCCESS - Director Mode Active")
        elif gen_by == "v1.5-v2-unified":
             print("❌ RESULT: FAIL - Legacy V2 detected")
        else:
             print(f"⚠️ RESULT: UNKNOWN - {gen_by}")

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    inspect_metadata_v2()
